### ISSUE TITLE
Fehler bei Demo Seite

### ISSUE THREAD

**Issue by midzer** [freifunkMUC/nodelist-ffm#12]
Beim Ansurfen der Demo Seite bekomme ich folgenden Fehler:

"This site can’t provide a secure connection"

Browser: Chromium

**Comment by skruppy** [comment]
Hi midzer,

ja das Problem ist bekannt. Das liegt an meiner Paranoia Webserver Config. Die erlaubt keine EC (hoffentlich kommt bald TLS 1.3 für vernünftige Kurven). Ggf. kann man die Node List ja auch auf der ffmuc Seite gehostet werden (mit bauen/testen in travis und automatischem deployment).

**Comment by skruppy** [comment]
Sooo, jetzt kann der Server X25519 und damit habe ich auch ECDHE aktiviert. Es [funktioniert](https://www.ssllabs.com/ssltest/analyze.html?d=onmars.eu) also jetzt auch wieder in Chromium (Es geht sogar über TLS 1.3 draft :) )
