### ISSUE TITLE
wrong "last seen" date for all nodes

### ISSUE THREAD

**Issue by rotanid** [freifunkMUC/nodelist-ffm#3]
it seems the "last seen" value is wrong all or at least most of the nodes.
it shows 25.01.2016 at the moment, correct would be 26.02.2016
doing a quick look at the main.js i couldn't see an obvious issue...

**Comment by gomaaz** [comment]
Same here.

**Comment by skruppy** [comment]
What I found so far:
- Data/JSON from ffmuc is correct
- The correct data gets passed to W2UI
- Seems to affect every row

My guess is a problem with W2UI. When I have more time, I will try a newer W2UI Version. (For now, I haven't fount an bug oder PR for this problem in the W2UI repo)

**Comment by gomaaz** [comment]
I also checked our json and it is also correct
and yes it affects every row

**Comment by rotanid** [comment]
in the meantime, the last seen date switched to 05.03.2016 , crazy...

**Comment by rotanid** [comment]
@Skrupellos apparently the dates for both last seen and first seen are wrong by about a month all the time. perhaps that information helps narrowing it down?

**Comment by rotanid** [comment]
w2ui 1.4.3 got released a week ago. maybe that fixes it?

@Skrupellos apparently the dates for both last seen and first seen are wrong by about a month all the time. perhaps that information helps narrowing it down?

**Comment by rotanid** [comment]
@Skrupellos apparently the dates for both last seen and first seen are wrong by about a month all the time. perhaps that information helps narrowing it down?

(i wrote something wrong in an earlier version of this comment)

**Comment by skruppy** [comment]
Currently I'm waiting for https://github.com/vitmalina/w2ui/issues/1272 . After the 22th Aug, I have time to test a new (released or dev) version.

**Comment by rotanid** [comment]
@Skrupellos it seems 1.5 has been released :)

**Comment by skruppy** [comment]
So, I guess the problem now fixed in branch feature/w2ui-1.5. Can anyone confirm this?

A test instance can be found at https://onmars.eu/ffmuc/list/ (my crypto does not work with chromium).

**Comment by rotanid** [comment]
working there, too: https://nodelist.tecff.de/
closing.
