### ISSUE TITLE
add Freifunk Nord to Readme

### ISSUE THREAD

**Issue by rubo77** [freifunkMUC/nodelist-ffm#9]
See https://github.com/Freifunk-Nord/nodelist/blob/d78b583349db05a6fec44c6c624665b68363ebfd/app/scripts/config.js

or https://github.com/Freifunk-Nord/nord-nodelist-config/blob/master/config.js

**Comment by rotanid** [comment]
maintainer @Skrupellos fixed it with commit d0dc7dc2228a014ae763918e3ecdf8ca977e54c3, can be closed.

**Comment by skruppy** [comment]
Uh, I totally forgot to close the issue. thx @rotanid.
